In [33]:
from  sklearn.impute import SimpleImputer
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np

In [63]:
df = pd.read_csv(r"C:\Users\babus\Data_Spark\Data_analysis_practice\Data Collection\claimants.csv")
df_1 = df.copy()
df_2 = df.copy()
df_3 = df.copy()
df_4 = df.copy()

In [4]:
df

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [5]:
df.isnull().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [6]:
df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [7]:
# drop a column ['CLMAGE']
df.drop(columns=['CLMAGE'],inplace=True)

In [8]:
df

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT    LOSS
0           5         0     0.0       1.0       0.0  34.940
1           3         1     1.0       0.0       0.0   0.891
2          66         1     0.0       1.0       0.0   0.330
3          70         0     0.0       1.0       1.0   0.037
4          96         1     0.0       1.0       0.0   0.038
...       ...       ...     ...       ...       ...     ...
1335    34100         1     0.0       1.0       0.0   0.576
1336    34110         0     1.0       1.0       0.0   3.705
1337    34113         1     1.0       1.0       0.0   0.099
1338    34145         0     1.0       0.0       0.0   3.177
1339    34153         1     1.0       1.0       0.0   0.688

[1340 rows x 6 columns]

In [9]:
df.isna().sum()

CASENUM      0
ATTORNEY     0
CLMSEX      12
CLMINSUR    41
SEATBELT    48
LOSS         0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT    LOSS
0           5         0     0.0       1.0       0.0  34.940
1           3         1     1.0       0.0       0.0   0.891
2          66         1     0.0       1.0       0.0   0.330
3          70         0     0.0       1.0       1.0   0.037
4          96         1     0.0       1.0       0.0   0.038
...       ...       ...     ...       ...       ...     ...
1335    34100         1     0.0       1.0       0.0   0.576
1336    34110         0     1.0       1.0       0.0   3.705
1337    34113         1     1.0       1.0       0.0   0.099
1338    34145         0     1.0       0.0       0.0   3.177
1339    34153         1     1.0       1.0       0.0   0.688

[1269 rows x 6 columns]

In [12]:
df.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
LOSS        0
dtype: int64

In [13]:
df_1 = pd.read_csv(r"C:\Users\babus\Data_Spark\Data_analysis_practice\Data Collection\claimants.csv")

In [14]:
df_1

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [15]:
df_1.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

# Mean Imputter  -SimpleImputer

In [17]:
mean_imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
df_1['CLMAGE'] = pd.DataFrame(mean_imputer.fit_transform(df_1[['CLMAGE']]))

In [18]:
df_1.isna().sum()

CASENUM      0
ATTORNEY     0
CLMSEX      12
CLMINSUR    41
SEATBELT    48
CLMAGE       0
LOSS         0
dtype: int64

In [19]:
median_imputer = SimpleImputer(missing_values=np.nan,strategy='median')
df_1['CLMSEX'] = pd.DataFrame(median_imputer.fit_transform(df_1[['CLMSEX']]))

In [20]:
df_1.isna().sum()

CASENUM      0
ATTORNEY     0
CLMSEX       0
CLMINSUR    41
SEATBELT    48
CLMAGE       0
LOSS         0
dtype: int64

In [21]:
mode_imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_1['CLMINSUR'] = pd.DataFrame(median_imputer.fit_transform(df_1[['CLMINSUR']]))

In [22]:
df_1.isna().sum()

CASENUM      0
ATTORNEY     0
CLMSEX       0
CLMINSUR     0
SEATBELT    48
CLMAGE       0
LOSS         0
dtype: int64

In [23]:
mode_imputer = SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=10)
df_1['SEATBELT'] = pd.DataFrame(median_imputer.fit_transform(df_1[['SEATBELT']]))

In [24]:
df_1.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

# fillna

In [26]:
df_2.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [34]:
df_2['CLMSEX'].fillna(1,inplace=True)
df_2['CLMINSUR'].fillna(2,inplace=True)
df_2['SEATBELT'].fillna(3,inplace=True)
df_2['CLMAGE'].fillna(4,inplace=True)

In [32]:
df_2.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [47]:
df_3['CLMSEX'].fillna(df_3['CLMSEX'].mean(),inplace=True)
df_3['CLMINSUR'].fillna(df_3['CLMINSUR'].median(),inplace=True)
df_3['SEATBELT'].fillna(df_3['SEATBELT'].mode()[0],inplace=True)
df_3['CLMAGE'].fillna(df_3['CLMAGE'].mean(),inplace=True)

In [48]:
df_3.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [52]:
mean = df_4['CLMSEX'].mean()
df_4['CLMSEX'].fillna(mean,inplace=True)
df_4.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX        0
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [53]:
df_3.nunique()

CASENUM     1283
ATTORNEY       2
CLMSEX         2
CLMINSUR       2
SEATBELT       2
CLMAGE        68
LOSS         916
dtype: int64

In [68]:
# Duplicates  Checking

In [65]:
df_3.duplicated().sum()

np.int64(1)

In [67]:
df_3[df_3.duplicated()]

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
1340    34153         1     1.0       1.0       0.0    30.0  0.688

In [ ]:
# Droping Duplicates

In [69]:
df_3.drop_duplicates(inplace=True)

In [70]:
df_3.duplicated().sum()

np.int64(0)

In [71]:
df_3[df_3.duplicated()]

Empty DataFrame
Columns: [CASENUM, ATTORNEY, CLMSEX, CLMINSUR, SEATBELT, CLMAGE, LOSS]
Index: []