In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\DataSpark\DAta_preproessing\customer (1).csv")

In [3]:
df

     4000001  Kristina    Chung  55                       Pilot      india
0    4000002     Paige     Chen  74                     Teacher         uk
1    4000003    Sherri   Melton  34                 Firefighter         us
2    4000004  Gretchen     Hill  66  Computer hardware engineer      china
3    4000005     Karen  Puckett  74                      Lawyer     africa
4    4000006   Patrick     Song  42                Veterinarian  australia
..       ...       ...      ...  ..                         ...        ...
457  4000459  Gretchen  Francis  60                  Politician    ireland
458  4000460    Cheryl     Horn  40                Veterinarian    ireland
459  4000461    Audrey  Forrest  50                   Architect    ireland
460  4000462      Alan    Levin  43                Statistician    ireland
461  4000463     Wayne   Weiner  70                       Actor    ireland

[462 rows x 6 columns]

In [4]:
df.shape

(462, 6)

In [5]:
df.size

2772

In [6]:
df.head(6)

   4000001  Kristina     Chung  55                       Pilot      india
0  4000002     Paige      Chen  74                     Teacher         uk
1  4000003    Sherri    Melton  34                 Firefighter         us
2  4000004  Gretchen      Hill  66  Computer hardware engineer      china
3  4000005     Karen   Puckett  74                      Lawyer     africa
4  4000006   Patrick      Song  42                Veterinarian  australia
5  4000007     Elsie  Hamilton  43                       Pilot    ireland

In [7]:
df.tail(7)

     4000001  Kristina    Chung  55         Pilot    india
455  4000457   Bernard     Pate  34        Doctor  ireland
456  4000458    Harold  Burnett  40      Musician  ireland
457  4000459  Gretchen  Francis  60    Politician  ireland
458  4000460    Cheryl     Horn  40  Veterinarian  ireland
459  4000461    Audrey  Forrest  50     Architect  ireland
460  4000462      Alan    Levin  43  Statistician  ireland
461  4000463     Wayne   Weiner  70         Actor  ireland

In [8]:
df.columns

Index(['4000001', 'Kristina', 'Chung', '55', 'Pilot', 'india'], dtype='object')

In [9]:
df = pd.read_csv(r"D:\DataSpark\DAta_preproessing\customer (1).csv" ,names=['Id','First_Name','Last_Name','Age','Professions','Locations'])

In [10]:
df

          Id First_Name Last_Name  Age                 Professions Locations
0    4000001   Kristina     Chung   55                       Pilot     india
1    4000002      Paige      Chen   74                     Teacher        uk
2    4000003     Sherri    Melton   34                 Firefighter        us
3    4000004   Gretchen      Hill   66  Computer hardware engineer     china
4    4000005      Karen   Puckett   74                      Lawyer    africa
..       ...        ...       ...  ...                         ...       ...
458  4000459   Gretchen   Francis   60                  Politician   ireland
459  4000460     Cheryl      Horn   40                Veterinarian   ireland
460  4000461     Audrey   Forrest   50                   Architect   ireland
461  4000462       Alan     Levin   43                Statistician   ireland
462  4000463      Wayne    Weiner   70                       Actor   ireland

[463 rows x 6 columns]

In [11]:
df.iloc[2:11][['First_Name','Professions']]

   First_Name                 Professions
2      Sherri                 Firefighter
3    Gretchen  Computer hardware engineer
4       Karen                      Lawyer
5     Patrick                Veterinarian
6       Elsie                       Pilot
7       Hazel                   Carpenter
8     Malcolm                      Artist
9     Dolores                      Writer
10    Francis                   Therapist

In [12]:
# SORTING
# ascending order
df.sort_values(by='Age',ascending=False).head()

          Id First_Name Last_Name  Age          Professions  Locations
88   4000089     Sherri    Sutton   75        Social worker         us
324  4000325       Ruth    Harmon   75               Artist  australia
274  4000275   Lawrence     Miles   74               Dancer     africa
258  4000259   Margaret   Burgess   74        Social worker     africa
241  4000242       Edna     Hoyle   74  Electrical engineer     africa

In [13]:
# descending Order
df.sort_values(by='Age',ascending=True).head()

          Id First_Name  Last_Name  Age     Professions  Locations
51   4000052    Shirley    Merritt   21        Reporter         uk
348  4000349    Russell     Dalton   21  Civil engineer  australia
291  4000292      Donna       Rice   21   Social worker  australia
289  4000290       Gail  Whitehead   21           Nurse  australia
450  4000451    Russell       Hess   21       Architect    ireland

In [14]:
df.sort_values(by='Age',ascending=False).head(5)[['Locations','First_Name']]

     Locations First_Name
88          us     Sherri
324  australia       Ruth
274     africa   Lawrence
258     africa   Margaret
241     africa       Edna

In [15]:
df.sort_values(by='Age',ascending=False).iloc[2:11][['First_Name','Professions']].head(5)

    First_Name          Professions
274   Lawrence               Dancer
258   Margaret        Social worker
241       Edna  Electrical engineer
391       Emma                Pilot
306      Karen               Farmer

In [16]:
df.sort_values(by=['First_Name','Age'])

          Id First_Name   Last_Name  Age              Professions  Locations
271  4000272       Adam  Washington   54      Electrical engineer     africa
461  4000462       Alan       Levin   43             Statistician    ireland
422  4000423       Alan      O'Neal   59                    Pilot    ireland
20   4000021       Alex         May   39  Environmental scientist      india
232  4000233       Alex       Henry   67           Police officer     africa
..       ...        ...         ...  ...                      ...        ...
293  4000294      Wendy      Cherry   70             Loan officer  australia
22   4000023     Wesley      Teague   42                Carpenter      india
246  4000247     Wesley     Shaffer   58                   Farmer     africa
252  4000253     Wesley       Moser   64                   Doctor     africa
49   4000050    William       Jones   53             Photographer         uk

[463 rows x 6 columns]

In [17]:
df.sort_values(by=['Age','First_Name'])

          Id First_Name  Last_Name  Age              Professions  Locations
291  4000292      Donna       Rice   21            Social worker  australia
289  4000290       Gail  Whitehead   21                    Nurse  australia
175  4000176    Kristin  Alexander   21                    Coach      china
348  4000349    Russell     Dalton   21           Civil engineer  australia
450  4000451    Russell       Hess   21                Architect    ireland
..       ...        ...        ...  ...                      ...        ...
1    4000002      Paige       Chen   74                  Teacher         uk
219  4000220    Rebecca      Heath   74  Environmental scientist     africa
147  4000148       Troy      Jones   74                Secretary      china
324  4000325       Ruth     Harmon   75                   Artist  australia
88   4000089     Sherri     Sutton   75            Social worker         us

[463 rows x 6 columns]

In [18]:
df.sort_values(by=['Age','First_Name'],ascending=[True,True]).head(10)

          Id First_Name  Last_Name  Age     Professions  Locations
291  4000292      Donna       Rice   21   Social worker  australia
289  4000290       Gail  Whitehead   21           Nurse  australia
175  4000176    Kristin  Alexander   21           Coach      china
348  4000349    Russell     Dalton   21  Civil engineer  australia
450  4000451    Russell       Hess   21       Architect    ireland
51   4000052    Shirley    Merritt   21        Reporter         uk
217  4000218      Brett     Snyder   22          Doctor     africa
53   4000054     Judith     Cooper   22       Economist         uk
358  4000359       Leon     Bender   22     Firefighter  australia
151  4000152    Vincent    Goldman   22     Electrician      china

In [20]:
df.sort_values(by='First_Name',ignore_index='True')

          Id First_Name   Last_Name  Age              Professions  Locations
0    4000272       Adam  Washington   54      Electrical engineer     africa
1    4000462       Alan       Levin   43             Statistician    ireland
2    4000423       Alan      O'Neal   59                    Pilot    ireland
3    4000021       Alex         May   39  Environmental scientist      india
4    4000233       Alex       Henry   67           Police officer     africa
..       ...        ...         ...  ...                      ...        ...
458  4000294      Wendy      Cherry   70             Loan officer  australia
459  4000253     Wesley       Moser   64                   Doctor     africa
460  4000247     Wesley     Shaffer   58                   Farmer     africa
461  4000023     Wesley      Teague   42                Carpenter      india
462  4000050    William       Jones   53             Photographer         uk

[463 rows x 6 columns]

In [128]:
df1 = df.copy()
df1

          Id First_Name Last_Name  Age                 Professions Locations
0    4000001   Kristina     Chung   55                       Pilot     india
1    4000002      Paige      Chen   74                     Teacher        uk
2    4000003     Sherri    Melton   34                 Firefighter        us
3    4000004   Gretchen      Hill   66  Computer hardware engineer     china
4    4000005      Karen   Puckett   74                      Lawyer    africa
..       ...        ...       ...  ...                         ...       ...
458  4000459   Gretchen   Francis   60                  Politician   ireland
459  4000460     Cheryl      Horn   40                Veterinarian   ireland
460  4000461     Audrey   Forrest   50                   Architect   ireland
461  4000462       Alan     Levin   43                Statistician   ireland
462  4000463      Wayne    Weiner   70                       Actor   ireland

[463 rows x 6 columns]

In [129]:
df1.sort_values(by='First_Name')

          Id First_Name   Last_Name  Age              Professions  Locations
271  4000272       Adam  Washington   54      Electrical engineer     africa
461  4000462       Alan       Levin   43             Statistician    ireland
422  4000423       Alan      O'Neal   59                    Pilot    ireland
20   4000021       Alex         May   39  Environmental scientist      india
232  4000233       Alex       Henry   67           Police officer     africa
..       ...        ...         ...  ...                      ...        ...
293  4000294      Wendy      Cherry   70             Loan officer  australia
252  4000253     Wesley       Moser   64                   Doctor     africa
246  4000247     Wesley     Shaffer   58                   Farmer     africa
22   4000023     Wesley      Teague   42                Carpenter      india
49   4000050    William       Jones   53             Photographer         uk

[463 rows x 6 columns]

df1 = df.sort_values(by="Locations",inplacce=True) 
df1

In [130]:
df1.sort_values(by="Locations",inplace=True) 
df1

          Id First_Name Last_Name  Age                  Professions Locations
231  4000232     Marvin   Parrott   67                       Doctor    africa
259  4000260     Philip       Liu   59                        Nurse    africa
258  4000259   Margaret   Burgess   74                Social worker    africa
257  4000258     Justin   Spencer   67                    Economist    africa
256  4000257     Monica    Dodson   58                          NaN    africa
..       ...        ...       ...  ...                          ...       ...
84   4000085       Leon   Pearson   24                    Physicist        us
83   4000084      Diana     Moore   44  Computer support specialist        us
82   4000083       Faye    Sparks   61               Civil engineer        us
90   4000091      Kelly    Bowman   69             Childcare worker        us
139  4000140     Sidney      Lane   54                 Statistician        us

[463 rows x 6 columns]

In [131]:
df

          Id First_Name Last_Name  Age                 Professions Locations
0    4000001   Kristina     Chung   55                       Pilot     india
1    4000002      Paige      Chen   74                     Teacher        uk
2    4000003     Sherri    Melton   34                 Firefighter        us
3    4000004   Gretchen      Hill   66  Computer hardware engineer     china
4    4000005      Karen   Puckett   74                      Lawyer    africa
..       ...        ...       ...  ...                         ...       ...
458  4000459   Gretchen   Francis   60                  Politician   ireland
459  4000460     Cheryl      Horn   40                Veterinarian   ireland
460  4000461     Audrey   Forrest   50                   Architect   ireland
461  4000462       Alan     Levin   43                Statistician   ireland
462  4000463      Wayne    Weiner   70                       Actor   ireland

[463 rows x 6 columns]

<!-- na positions -->
<!--  -->

In [133]:
df.sort_values(by="Professions",na_position='first')

          Id First_Name   Last_Name  Age Professions  Locations
256  4000257     Monica      Dodson   58         NaN     africa
26   4000027     Marcia       Walsh   64  Accountant      india
277  4000278   Meredith      Bowles   62  Accountant     africa
334  4000335        Jim   Singleton   55  Accountant  australia
281  4000282     Ashley     Hendrix   50  Accountant     africa
..       ...        ...         ...  ...         ...        ...
11   4000012      Sandy      Raynor   26      Writer      india
9    4000010    Dolores  McLaughlin   60      Writer      india
167  4000168       Jose       Sykes   47      Writer      china
338  4000339      Kerry        Huff   38      Writer  australia
50   4000051  Frederick       Baker   52      Writer         uk

[463 rows x 6 columns]

In [135]:
df.sort_values(by="Professions",na_position='last').tail()

          Id First_Name   Last_Name  Age Professions  Locations
9    4000010    Dolores  McLaughlin   60      Writer      india
167  4000168       Jose       Sykes   47      Writer      china
338  4000339      Kerry        Huff   38      Writer  australia
50   4000051  Frederick       Baker   52      Writer         uk
256  4000257     Monica      Dodson   58         NaN     africa

<!-- UNIQUE -->
<!-- FIND ALL UNIQUE VALUESIN A COLUMNS (DISTINCT) -->

In [136]:
df['Professions'].unique()

array(['Pilot', 'Teacher', 'Firefighter', 'Computer hardware engineer',
       'Lawyer', 'Veterinarian', 'Carpenter', 'Artist', 'Writer',
       'Therapist', 'Musician', 'Pharmacist',
       'Computer support specialist', 'Childcare worker',
       'Financial analyst', 'Engineering technician',
       'Environmental scientist', 'Doctor', 'Dancer', 'Accountant',
       'Economist', 'Real estate agent', 'Human resources assistant',
       'Civil engineer', 'Reporter', 'Agricultural and food scientist',
       'Police officer', 'Secretary', 'Physicist',
       'Computer software engineer', 'Photographer', 'Social worker',
       'Actor', 'Athlete', 'Judge', 'Recreation and fitness worker',
       'Architect', 'Loan officer', 'Politician', 'Librarian', 'Nurse',
       'Designer', 'Coach', 'Automotive mechanic', 'Electrician',
       'Statistician', 'Psychologist', 'Chemist', 'Electrical engineer',
       'Farmer', nan], dtype=object)

<!-- COUNT THE NUMBER OF UNIOQUE VALUES IN COLUMN-->

In [137]:
df['Professions'].nunique()

50

In [138]:
df['Locations'].nunique()

7

<!-- VALUES COUNTS -->
<!-- COUNT THE OCCURES -->

In [139]:
df['Locations'].value_counts()

Locations
australia    104
africa        90
us            78
ireland       77
china         56
uk            37
india         21
Name: count, dtype: int64

In [140]:
df['Professions'].value_counts()

Professions
Childcare worker                   17
Musician                           15
Photographer                       15
Loan officer                       14
Veterinarian                       13
Pilot                              13
Doctor                             13
Actor                              12
Computer support specialist        12
Civil engineer                     11
Electrical engineer                11
Politician                         11
Statistician                       11
Economist                          10
Carpenter                          10
Lawyer                             10
Environmental scientist            10
Human resources assistant          10
Social worker                      10
Nurse                               9
Coach                               9
Designer                            9
Accountant                          9
Athlete                             9
Agricultural and food scientist     9
Engineering technician              9
Firefighter                         9
Recreation and fitness worker       9
Dancer                              9
Farmer                              8
Therapist                           8
Artist                              8
Pharmacist                          8
Librarian                           8
Electrician                         8
Physicist                           8
Architect                           8
Secretary                           8
Reporter                            8
Computer software engineer          7
Police officer                      7
Computer hardware engineer          7
Judge                               6
Automotive mechanic                 6
Chemist                             6
Real estate agent                   6
Teacher                             5
Writer                              5
Psychologist                        5
Financial analyst                   4
Name: count, dtype: int64

<!-- DISPLAY CUSTOMER FROM INDIA -->

In [141]:
df_india = df.loc[df['Locations'] == 'india']
df_india.head(10)

         Id First_Name   Last_Name  Age Professions Locations
0   4000001   Kristina       Chung   55       Pilot     india
7   4000008      Hazel      Bender   63   Carpenter     india
8   4000009    Malcolm      Wagner   39      Artist     india
9   4000010    Dolores  McLaughlin   60      Writer     india
10  4000011    Francis    McNamara   47   Therapist     india
11  4000012      Sandy      Raynor   26      Writer     india
12  4000013     Marion        Moon   41   Carpenter     india
13  4000014       Beth     Woodard   65    Musician     india
14  4000015      Julia       Desai   49    Musician     india
15  4000016     Jerome     Wallace   52  Pharmacist     india

<!-- reseting index -->
df_india.reset_index(inplace=True)

In [142]:
df_india.reset_index(inplace=True)
df_india

,index,Id,First_Name,Last_Name,Age,Professions,Locations
0,0,4000001,Kristina,Chung,55,Pilot,india
1,7,4000008,Hazel,Bender,63,Carpenter,india
2,8,4000009,Malcolm,Wagner,39,Artist,india
3,9,4000010,Dolores,McLaughlin,60,Writer,india
4,10,4000011,Francis,McNamara,47,Therapist,india
5,11,4000012,Sandy,Raynor,26,Writer,india
6,12,4000013,Marion,Moon,41,Carpenter,india
7,13,4000014,Beth,Woodard,65,Musician,india
8,14,4000015,Julia,Desai,49,Musician,india
9,15,4000016,Jerome,Wallace,52,Pharmacist,india
10,16,4000017,Neal,Lawrence,72,Computer support specialist,india
11,17,4000018,Jean,Griffin,45,Childcare worker,india
12,18,4000019,Kristine,Dougherty,63,Financial analyst,india
13,19,4000020,Crystal,Powers,67,Engineering technician,india
14,20,4000021,Alex,May,39,Environmental scientist,india
15,21,4000022,Eric,Steele,66,Doctor,india
16,22,4000023,Wesley,Teague,42,Carpenter,india
17,23,4000024,Franklin,Vick,28,Dancer,india
18,24,4000025,Claire,Gallagher,42,Musician,india
19,25,4000026,Marian,Solomon,27,Lawyer,india
20,26,4000027,Marcia,Walsh,64,Accountant,india

In [143]:
# # df_india.reset_index(inplace=True)
# df_india
df_india.reset_index(drop=True)

,index,Id,First_Name,Last_Name,Age,Professions,Locations
0,0,4000001,Kristina,Chung,55,Pilot,india
1,7,4000008,Hazel,Bender,63,Carpenter,india
2,8,4000009,Malcolm,Wagner,39,Artist,india
3,9,4000010,Dolores,McLaughlin,60,Writer,india
4,10,4000011,Francis,McNamara,47,Therapist,india
5,11,4000012,Sandy,Raynor,26,Writer,india
6,12,4000013,Marion,Moon,41,Carpenter,india
7,13,4000014,Beth,Woodard,65,Musician,india
8,14,4000015,Julia,Desai,49,Musician,india
9,15,4000016,Jerome,Wallace,52,Pharmacist,india
10,16,4000017,Neal,Lawrence,72,Computer support specialist,india
11,17,4000018,Jean,Griffin,45,Childcare worker,india
12,18,4000019,Kristine,Dougherty,63,Financial analyst,india
13,19,4000020,Crystal,Powers,67,Engineering technician,india
14,20,4000021,Alex,May,39,Environmental scientist,india
15,21,4000022,Eric,Steele,66,Doctor,india
16,22,4000023,Wesley,Teague,42,Carpenter,india
17,23,4000024,Franklin,Vick,28,Dancer,india
18,24,4000025,Claire,Gallagher,42,Musician,india
19,25,4000026,Marian,Solomon,27,Lawyer,india
20,26,4000027,Marcia,Walsh,64,Accountant,india

#display the FirstName and LastName of people whose profession is "Dancer"

In [149]:
df_india
df_india.loc[
    df_india['Professions'].str.strip().str.lower() == 'dancer'
][['First_Name','Last_Name']]

   First_Name Last_Name
17   Franklin      Vick

In [152]:
df.loc[df['Professions'] == 'Dancer'][['First_Name','Last_Name']].reset_index(drop=True)

  First_Name Last_Name
0   Franklin      Vick
1       Kurt   Cassidy
2      Danny     Byrne
3     Ronnie    Atkins
4   Lawrence     Miles
5        Max  Robinson
6      Tracy     Cates
7  Christina    Morris
8      Paige    Henson

In [153]:
df.shape[0]

463

In [154]:
df.shape[1]

6

In [155]:
df.shape

(463, 6)

<!-- find count of teachers from india -->

In [156]:
len(df.loc[(df['Professions'] == 'Teacher') & (df['Locations'] == 'uk')])

2

In [157]:
df.isna()

        Id  First_Name  Last_Name    Age  Professions  Locations
0    False       False      False  False        False      False
1    False       False      False  False        False      False
2    False       False      False  False        False      False
3    False       False      False  False        False      False
4    False       False      False  False        False      False
..     ...         ...        ...    ...          ...        ...
458  False       False      False  False        False      False
459  False       False      False  False        False      False
460  False       False      False  False        False      False
461  False       False      False  False        False      False
462  False       False      False  False        False      False

[463 rows x 6 columns]

In [158]:
df.loc[df['Professions'].isna()]

          Id First_Name Last_Name  Age Professions Locations
256  4000257     Monica    Dodson   58         NaN    africa

In [159]:
df.loc[df['First_Name'].isna()]

Empty DataFrame
Columns: [Id, First_Name, Last_Name, Age, Professions, Locations]
Index: []

In [164]:
df[['Id','First_Name','Last_Name','Age','Professions','Locations']].isna().sum()

Id             0
First_Name     0
Last_Name      0
Age            0
Professions    1
Locations      0
dtype: int64

<!-- Duplicates
-->

In [165]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
458    False
459    False
460    False
461    False
462    False
Length: 463, dtype: bool

In [166]:
df.duplicated().sum()

np.int64(0)

In [167]:
df[df.duplicated()]

Empty DataFrame
Columns: [Id, First_Name, Last_Name, Age, Professions, Locations]
Index: []

In [168]:
# CHECK DUPLICATE ON SPECIFIED COLUMNS
df[df.duplicated(subset='Professions')]

          Id First_Name Last_Name  Age   Professions Locations
6    4000007      Elsie  Hamilton   43         Pilot   ireland
11   4000012      Sandy    Raynor   26        Writer     india
12   4000013     Marion      Moon   41     Carpenter     india
14   4000015      Julia     Desai   49      Musician     india
22   4000023     Wesley    Teague   42     Carpenter     india
..       ...        ...       ...  ...           ...       ...
458  4000459   Gretchen   Francis   60    Politician   ireland
459  4000460     Cheryl      Horn   40  Veterinarian   ireland
460  4000461     Audrey   Forrest   50     Architect   ireland
461  4000462       Alan     Levin   43  Statistician   ireland
462  4000463      Wayne    Weiner   70         Actor   ireland

[412 rows x 6 columns]

In [169]:
df2 = df.copy()

In [170]:
df['Professions'].nunique()

50

In [171]:
df.duplicated(subset='Professions').sum()

np.int64(412)

In [174]:
# FOR RREMOVING DUPLICATES
df3 = df1.copy()
df3

          Id First_Name Last_Name  Age                  Professions Locations
231  4000232     Marvin   Parrott   67                       Doctor    africa
259  4000260     Philip       Liu   59                        Nurse    africa
258  4000259   Margaret   Burgess   74                Social worker    africa
257  4000258     Justin   Spencer   67                    Economist    africa
256  4000257     Monica    Dodson   58                          NaN    africa
..       ...        ...       ...  ...                          ...       ...
84   4000085       Leon   Pearson   24                    Physicist        us
83   4000084      Diana     Moore   44  Computer support specialist        us
82   4000083       Faye    Sparks   61               Civil engineer        us
90   4000091      Kelly    Bowman   69             Childcare worker        us
139  4000140     Sidney      Lane   54                 Statistician        us

[463 rows x 6 columns]

In [176]:
df3.drop_duplicates()

          Id First_Name Last_Name  Age                  Professions Locations
231  4000232     Marvin   Parrott   67                       Doctor    africa
259  4000260     Philip       Liu   59                        Nurse    africa
258  4000259   Margaret   Burgess   74                Social worker    africa
257  4000258     Justin   Spencer   67                    Economist    africa
256  4000257     Monica    Dodson   58                          NaN    africa
..       ...        ...       ...  ...                          ...       ...
84   4000085       Leon   Pearson   24                    Physicist        us
83   4000084      Diana     Moore   44  Computer support specialist        us
82   4000083       Faye    Sparks   61               Civil engineer        us
90   4000091      Kelly    Bowman   69             Childcare worker        us
139  4000140     Sidney      Lane   54                 Statistician        us

[463 rows x 6 columns]

In [177]:
# DROP_COULMNS

df.drop(['Id'],axis=1)
# axis = 1 --> column
# axis = 0 --> row

    First_Name Last_Name  Age                 Professions Locations
0     Kristina     Chung   55                       Pilot     india
1        Paige      Chen   74                     Teacher        uk
2       Sherri    Melton   34                 Firefighter        us
3     Gretchen      Hill   66  Computer hardware engineer     china
4        Karen   Puckett   74                      Lawyer    africa
..         ...       ...  ...                         ...       ...
458   Gretchen   Francis   60                  Politician   ireland
459     Cheryl      Horn   40                Veterinarian   ireland
460     Audrey   Forrest   50                   Architect   ireland
461       Alan     Levin   43                Statistician   ireland
462      Wayne    Weiner   70                       Actor   ireland

[463 rows x 5 columns]

In [ ]:
df

In [ ]:
df

In [ ]:

df1

In [ ]:
df3

In [ ]:
df

In [ ]:
df2

In [178]:
df2.drop(['First_Name'],axis=1,inplace=True)

In [179]:
df2

          Id Last_Name  Age                 Professions Locations
0    4000001     Chung   55                       Pilot     india
1    4000002      Chen   74                     Teacher        uk
2    4000003    Melton   34                 Firefighter        us
3    4000004      Hill   66  Computer hardware engineer     china
4    4000005   Puckett   74                      Lawyer    africa
..       ...       ...  ...                         ...       ...
458  4000459   Francis   60                  Politician   ireland
459  4000460      Horn   40                Veterinarian   ireland
460  4000461   Forrest   50                   Architect   ireland
461  4000462     Levin   43                Statistician   ireland
462  4000463    Weiner   70                       Actor   ireland

[463 rows x 5 columns]

## QA

In [21]:
df

          Id First_Name Last_Name  Age                 Professions Locations
0    4000001   Kristina     Chung   55                       Pilot     india
1    4000002      Paige      Chen   74                     Teacher        uk
2    4000003     Sherri    Melton   34                 Firefighter        us
3    4000004   Gretchen      Hill   66  Computer hardware engineer     china
4    4000005      Karen   Puckett   74                      Lawyer    africa
..       ...        ...       ...  ...                         ...       ...
458  4000459   Gretchen   Francis   60                  Politician   ireland
459  4000460     Cheryl      Horn   40                Veterinarian   ireland
460  4000461     Audrey   Forrest   50                   Architect   ireland
461  4000462       Alan     Levin   43                Statistician   ireland
462  4000463      Wayne    Weiner   70                       Actor   ireland

[463 rows x 6 columns]

In [29]:
#find the first name and last name of the maximum aged person from the UK

max_age = df.loc[(df['Age'] > 70 ) & (df['Locations'] == 'uk')][['First_Name','Last_Name']]
max_age

   First_Name Last_Name
1       Paige      Chen
37       Beth    Walton

In [33]:
max_age = df.loc[(df['Age'] > 60 ) & (df['Locations'].str.lower() == 'uk')][['First_Name','Last_Name']]
max_age

   First_Name  Last_Name
1       Paige       Chen
37       Beth     Walton
40     Donald      Chung
42       Paul      Woods
43   Patricia     Mangum
48     Harvey  Underwood
61       Evan      Grant

In [43]:
#find the first name and last name of the maximum aged person from the UK
max_age = df.loc[
    (df['Locations'].str.lower() == 'uk') &
    (df['Age'] == df.loc[df['Locations'].str.lower() == 'uk','Age'].max())]
    [['First_Name','Last_Name']
]
max_age

  First_Name Last_Name
1      Paige      Chen

In [54]:
#find the number of persons from China  way--1
len(df.loc[df['Locations'].str.lower() == 'china'])

56

In [61]:
# way -- 2
df['Locations'].str.lower().value_counts()['china']

np.int64(56)

In [62]:
# 1.Find the number of persons from India.
len(df.loc[df['Locations'].str.upper() == 'INDIA'])

21

In [63]:
df['Locations'].str.lower().value_counts()['india']

np.int64(21)

In [65]:
# 2.Display the details of persons from the US.
df.loc[df['Locations'].str.lower() == 'us']

          Id First_Name Last_Name  Age                  Professions Locations
2    4000003     Sherri    Melton   34                  Firefighter        us
63   4000064     Calvin      Diaz   65                      Athlete        us
64   4000065     Eugene    Graham   52               Police officer        us
65   4000066     Vickie   Watkins   55  Computer support specialist        us
66   4000067       Luis    Hinton   69             Childcare worker        us
..       ...        ...       ...  ...                          ...       ...
135  4000136     Dianne    Norman   68                 Veterinarian        us
136  4000137     Rhonda      Chan   34                   Pharmacist        us
137  4000138     Tamara      Hunt   25                 Psychologist        us
138  4000139       Mary      Byrd   34      Environmental scientist        us
139  4000140     Sidney      Lane   54                 Statistician        us

[78 rows x 6 columns]

In [66]:
df.loc[
    df['Locations'].str.strip().str.upper() == 'US',['First_Name','Professions']
]

    First_Name                  Professions
2       Sherri                  Firefighter
63      Calvin                      Athlete
64      Eugene               Police officer
65      Vickie  Computer support specialist
66        Luis             Childcare worker
..         ...                          ...
135     Dianne                 Veterinarian
136     Rhonda                   Pharmacist
137     Tamara                 Psychologist
138       Mary      Environmental scientist
139     Sidney                 Statistician

[78 rows x 2 columns]

In [69]:
# 3.Display the first name, last name, and age of all persons from China in ascending order of age.
df.loc[
    df['Locations'].str.strip().str.lower() == 'china',
    ['First_Name','Last_Name','Age']
].sort_values(by='Age').head()

    First_Name  Last_Name  Age
175    Kristin  Alexander   21
151    Vincent    Goldman   22
153     Milton      Starr   23
144      Roger      Hanna   23
191     Alison  MacDonald   26

In [70]:
# 4.Display the details of the oldest person from Ireland.
df.loc[
    df['Locations'].str.strip().str.lower() == 'ireland'
].sort_values('Age',ascending=False).head(1)

          Id First_Name Last_Name  Age Professions Locations
391  4000392       Emma     Olson   74       Pilot   ireland

In [76]:
ireland = df.loc[
    df['Locations'].str.strip().str.lower() == 'ireland'
]
old_irl = ireland.loc[
    ireland['Age'] == ireland['Age'].max()
]
old_irl

          Id First_Name Last_Name  Age Professions Locations
391  4000392       Emma     Olson   74       Pilot   ireland
403  4000404   Clarence    Massey   74  Politician   ireland

In [79]:
# 5.Display the profession of the youngest person from India.
india = df.loc[
    df['Locations'].str.strip().str.lower() == 'india'
]
yng_per = india.loc[
    india['Age'] == india['Age'].min()
]
yng_per['Professions']

11    Writer
Name: Professions, dtype: object

In [81]:
# 6.Display the details of all persons whose age is greater than 70.
df.loc[
    df['Age'] > 70
].head()

         Id First_Name Last_Name  Age                  Professions Locations
1   4000002      Paige      Chen   74                      Teacher        uk
4   4000005      Karen   Puckett   74                       Lawyer    africa
16  4000017       Neal  Lawrence   72  Computer support specialist     india
37  4000038       Beth    Walton   73                  Firefighter        uk
86  4000087      Steve    Graves   73                        Nurse        us

In [85]:
# 7.Display the first name and profession of persons whose age is greater than 50 and whose country is China.
df.loc[
    (df['Age'] > 50 ) & (df['Locations'].str.strip().str.lower() == 'china'),['First_Name','Professions']
].head(5)

    First_Name                 Professions
3     Gretchen  Computer hardware engineer
140       Jeff                     Chemist
141     Sandra                Photographer
143    Raymond                       Coach
146      Kathy                  Pharmacist

In [86]:
# 8.Display the details of all persons whose profession is "Pilot".
df.loc[
df['Professions'].str.strip().str.lower() == 'pilot'
]

          Id First_Name Last_Name  Age Professions  Locations
0    4000001   Kristina     Chung   55       Pilot      india
6    4000007      Elsie  Hamilton   43       Pilot    ireland
228  4000229       Faye    Norman   64       Pilot     africa
229  4000230      Kathy     Burch   28       Pilot     africa
250  4000251     Jeremy     House   61       Pilot     africa
270  4000271      Alice     Nance   59       Pilot     africa
321  4000322  Geraldine    Jensen   50       Pilot  australia
335  4000336     Steven   Ballard   62       Pilot  australia
391  4000392       Emma     Olson   74       Pilot    ireland
402  4000403        Leo  Lassiter   65       Pilot    ireland
422  4000423       Alan    O'Neal   59       Pilot    ireland
424  4000425       Dean      Lutz   26       Pilot    ireland
439  4000440     Hannah  Langston   25       Pilot    ireland

In [88]:
# 9.Display the details of all teachers from the UK.
df.loc[
    (df['Professions'].str.strip().str.lower() == 'teacher') &
    (df['Locations'].str.strip().str.upper() == 'UK' )
]

         Id First_Name Last_Name  Age Professions Locations
1   4000002      Paige      Chen   74     Teacher        uk
62  4000063    Melinda   Proctor   27     Teacher        uk

In [92]:
# 10.Display the first name and last name of all accountants from India.
df.loc[
    (df['Professions'].notna() & df['Locations'].notna() )&
    (df['Professions'].str.strip().str.lower() == 'accountant') & 
    (df['Locations'].str.strip().str.lower() == 'india'),
    ['First_Name','Last_Name']
]

   First_Name Last_Name
26     Marcia     Walsh

In [101]:
df.loc[
    ( df['Professions'].str.strip().str.lower() == 'musician') &
    ( df['Locations'].str.strip().str.lower() == 'india') 
]

         Id First_Name  Last_Name  Age Professions Locations
13  4000014       Beth    Woodard   65    Musician     india
14  4000015      Julia      Desai   49    Musician     india
24  4000025     Claire  Gallagher   42    Musician     india

In [109]:
# 11.Display the details of the two oldest musicians from India.
oldest = df.loc[
    ( df['Professions'].notna() & df['Locations'].notna() & df['Age'].notna() )&
    ( df['Professions'].str.strip().str.lower() == 'musician') &
    ( df['Locations'].str.strip().str.lower() == 'india') 
]
oldest.sort_values('Age',ascending=False).head(2)

         Id First_Name Last_Name  Age Professions Locations
13  4000014       Beth   Woodard   65    Musician     india
14  4000015      Julia     Desai   49    Musician     india

In [110]:
# 12.Check if there are any missing values in the dataset.
df.isna().sum()

Id             0
First_Name     0
Last_Name      0
Age            0
Professions    1
Locations      0
dtype: int64

In [113]:
# 13.Display the first name, profession, and age of all teachers in decreasing order of age.
teachers = df.loc[df['Professions'].str.strip().str.lower() == 'teacher']
teachers.sort_values(['Age'],ascending=[False])[['First_Name','Professions','Age']]

    First_Name Professions  Age
1        Paige     Teacher   74
374     Norman     Teacher   63
62     Melinda     Teacher   27
100      Scott     Teacher   27
396       Bill     Teacher   26

In [118]:
# 14.Display the first name of the oldest musician from India.
oldest =  df.loc[
    (df['Professions'].str.strip().str.lower() == 'musician') &
    (df['Locations'].str.strip().str.lower() == 'india') 
]
oldest.loc[
    oldest['Age'] == oldest['Age'].max(),['First_Name']
]

   First_Name
13       Beth

In [120]:
# 15.Display the first name of the youngest dancer from India.
youngst =  df.loc[
    (df['Professions'].str.strip().str.lower() == 'dancer') &
    (df['Locations'].str.strip().str.lower() == 'india') 
]
youngst.loc[
    youngst['Age'] == youngst['Age'].min(),['First_Name']
]

   First_Name
23   Franklin

In [123]:
# find the count of teachers from the UK
len(
    df.loc[
        ( df['Professions'].str.strip().str.lower() == 'teacher' ) &
        ( df['Locations'].str.strip().str.upper() == 'UK' )
    ]
)

2

In [125]:
d1

  name  roll_no
0    A        1
1    B        2

In [126]:
d2

  name  roll_no
0    C       99
1    D       98

In [127]:
d3

  batch location
0   BCA      blr
1   MCA   cochin

# concat()

In [ ]:
df =