In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\babus\Downloads\movies_cleaned (1).csv')
df

,1,The Nightmare Before Christmas,1993,3.9,4568.0
0,2,The Mummy,1932,3.5,4388.0
1,3,Orphans of the Storm,1921,3.2,9062.0
2,4,The Object of Beauty,1991,2.8,6150.0
3,5,Night Tide,1963,2.8,5126.0
4,6,One Magic Christmas,1985,3.8,5333.0
...,...,...,...,...,...
49584,49586,Winter Wonderland,2013,2.8,1812.0
49585,49587,Top Gear: Series 19: Africa Special,2013,3.4,6822.0
49586,49588,Fireplace For Your Home: Crackling Fireplace w...,2010,3.4,3610.0
49587,49589,Kate Plus Ei8ht,2010,2.7,2628.0
49588,49590,Kate Plus Ei8ht: Season 1,2010,2.7,2628.0

In [49]:
# 1.Give column name as Id, Movie, Year, Rating, Duration.

df = pd.read_csv(r'C:\Users\babus\Downloads\movies_cleaned (1).csv',
                 names=[ 'Id','Movie', 'Year','Rating', 'Duration']
                )
df

,Id,Movie,Year,Rating,Duration
0,1,The Nightmare Before Christmas,1993,3.9,4568.0
1,2,The Mummy,1932,3.5,4388.0
2,3,Orphans of the Storm,1921,3.2,9062.0
3,4,The Object of Beauty,1991,2.8,6150.0
4,5,Night Tide,1963,2.8,5126.0
...,...,...,...,...,...
49585,49586,Winter Wonderland,2013,2.8,1812.0
49586,49587,Top Gear: Series 19: Africa Special,2013,3.4,6822.0
49587,49588,Fireplace For Your Home: Crackling Fireplace w...,2010,3.4,3610.0
49588,49589,Kate Plus Ei8ht,2010,2.7,2628.0
49589,49590,Kate Plus Ei8ht: Season 1,2010,2.7,2628.0

In [50]:
# 2.Display the number of rows and number of columns.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49590 entries, 0 to 49589
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id        49590 non-null  int64
 1   Movie     49590 non-null  object
 2   Year      49590 non-null  int64
 3   Rating    49590 non-null  float64
 4   Duration  49590 non-null  float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1.9+ MB

In [51]:
# 3.Display the five observations that have highest duration.
x = df.sort_values(by='Duration',ascending = False)
x.head()

          Id                                 Movie  Year  Rating  Duration
22216  22217  Example 8 Hour 23.976 Remote Content  2010     3.0   28813.0
12303  12304                 Example 8 Hour 23.976  2010     3.2   28813.0
2423    2424                     The Best of Youth  2003     3.9   22024.0
22381  22382                        Heaven's Story  2010     2.3   16736.0
1831    1832               Dr. Mabuse: The Gambler  1922     3.1   16422.0

In [149]:
# 4.Remove if any duplicate exists and change the index accordingly.
df.duplicated().sum()
df = df.drop_duplicates(ignore_index=True)
df

,Id,Movie,Year,Rating,Duration
0,1,The Nightmare Before Christmas,1993,3.9,4568.0
1,2,The Mummy,1932,3.5,4388.0
2,3,Orphans of the Storm,1921,3.2,9062.0
3,4,The Object of Beauty,1991,2.8,6150.0
4,5,Night Tide,1963,2.8,5126.0
...,...,...,...,...,...
49585,49586,Winter Wonderland,2013,2.8,1812.0
49586,49587,Top Gear: Series 19: Africa Special,2013,3.4,6822.0
49587,49588,Fireplace For Your Home: Crackling Fireplace w...,2010,3.4,3610.0
49588,49589,Kate Plus Ei8ht,2010,2.7,2628.0
49589,49590,Kate Plus Ei8ht: Season 1,2010,2.7,2628.0

In [81]:
df.sort_values(by='Rating').head()

          Id                     Movie  Year  Rating  Duration
42115  42116       Sun Yaar Chill Maar  2007     1.4    2628.0
42160  42161       Sun Yaar Chill Maar  2007     1.4    2628.0
40934  40935                    Lagegi  2007     1.4    2628.0
40826  40827                    Lagegi  2007     1.4    2628.0
41396  41397  Meri Toh Lag Gayi Naukri  2011     1.5    2628.0

In [167]:
# 5.Rename the column name ‘Movie’ as Film.
x = df.rename(columns={'Movie':'Film'})
x
# y = df.drop(columns=[{'':0}])
# # y

,Id,Film,Year,Rating,Duration
0,1,The Nightmare Before Christmas,1993,3.9,4568.0
1,2,The Mummy,1932,3.5,4388.0
2,3,Orphans of the Storm,1921,3.2,9062.0
3,4,The Object of Beauty,1991,2.8,6150.0
4,5,Night Tide,1963,2.8,5126.0
...,...,...,...,...,...
49585,49586,Winter Wonderland,2013,2.8,1812.0
49586,49587,Top Gear: Series 19: Africa Special,2013,3.4,6822.0
49587,49588,Fireplace For Your Home: Crackling Fireplace w...,2010,3.4,3610.0
49588,49589,Kate Plus Ei8ht,2010,2.7,2628.0
49589,49590,Kate Plus Ei8ht: Season 1,2010,2.7,2628.0

In [55]:
# 6.Display all the observation starting from index 100 upto 200.
df.iloc[100:201]

,Id,Movie,Year,Rating,Duration
100,101,The Hunchback of Notre Dame,1923,3.5,6750.0
101,102,Heathers,1989,3.7,6193.0
102,103,Godzilla's Revenge,1969,3.3,4165.0
103,104,Hard Target,1993,3.4,5771.0
104,105,Henry: Portrait of a Serial Killer,1986,3.2,4938.0
...,...,...,...,...,...
196,197,The Toxic Avenger,1985,3.0,5243.0
197,198,The Two Jakes,1990,3.1,8251.0
198,199,Tales from the Crypt Presents: Bordello of Blood,1996,3.3,5189.0
199,200,Tales from the Hood,1995,3.4,5850.0
200,201,Star Trek IV: The Voyage Home,1986,3.6,7128.0

In [56]:
# 7.Display the name and releasing year of the film with maximum duration.

In [57]:
df.sort_values(by='Duration',ascending = False).loc[
df['Duration'] == df['Duration'].max() ,['Movie','Year']   
]

                                      Movie  Year
22216  Example 8 Hour 23.976 Remote Content  2010
12303                 Example 8 Hour 23.976  2010

In [144]:
# 8.Display the count of films released in each year.
df.loc[
    df['Year'] == df['Year']
]
# x = df['Year'].unique()
# x
x = df['Year'].value_counts().sort_index()
x

Year
1913       3
1914      20
1915       1
1916       1
1918       1
        ...
2010    5107
2011    5511
2012    4339
2013     981
2014       1
Name: count, Length: 101, dtype: int64

In [169]:
y = df[['Year']].value_counts()
y

Year
2011    5511
2010    5107
2009    4451
2012    4339
2008    3358
        ...
1926       2
1916       1
1915       1
1918       1
2014       1
Name: count, Length: 101, dtype: int64

In [174]:
# 9.Find the film released between 1986–1996 having highest duration.
df.loc[
    (df['Year'] >= 1986) &
    (df['Year'] <= 1996)
].sort_values(by='Duration',ascending = False).head(1)

        Id                         Film  Year  Rating  Duration
1648  1649  Dilwale Dulhania Le Jayenge  1995     4.0   11390.0

In [179]:
# 10 Find the films having duration greater than 7000 and rating above 3.5.
df.loc[
    (df['Duration'] > 7000) &
    (df['Rating'] >= 3.5 )
]

,Id,Film,Year,Rating,Duration
13,14,The Boys from Brazil,1978,3.6,7417.0
35,36,Into the Woods,1990,4.0,9077.0
41,42,In the Name of the Father,1993,3.9,7972.0
43,44,Do the Right Thing,1989,3.6,7186.0
47,48,Emma,1996,3.5,7260.0
...,...,...,...,...,...
45029,45030,Salinger,2013,4.0,7425.0
45479,45480,Madonna: MDNA: Live from Miami,2013,3.6,7191.0
46831,46832,WWE for All Mankind: The Life Career of Mick F...,2013,4.2,8066.0
46897,46898,The Last Tycoon,2012,3.8,7134.0
48713,48714,WWE: The Top 25 Rivalries in Wrestling History,2013,3.7,10228.0

In [73]:
# 11.Print the details about 5 films having less rating, display in the descending order.

low_r = df.sort_values(by='Rating').head()
low_r

          Id                     Movie  Year  Rating  Duration
42115  42116       Sun Yaar Chill Maar  2007     1.4    2628.0
42160  42161       Sun Yaar Chill Maar  2007     1.4    2628.0
40934  40935                    Lagegi  2007     1.4    2628.0
40826  40827                    Lagegi  2007     1.4    2628.0
41396  41397  Meri Toh Lag Gayi Naukri  2011     1.5    2628.0

In [177]:
high_r = df.sort_values(by='Rating',ascending = False).head()
high_r

          Id                   Film  Year  Rating  Duration
43443  43444              Blackfish  2013     4.5    4985.0
26483  26484               Sherlock  2010     4.5    2628.0
46400  46401  The Fosters: Season 1  2013     4.5    2628.0
46387  46388            The Fosters  2013     4.5    2628.0
13314  13315           Breaking Bad  2008     4.5    2628.0