In [1]:
import pandas as pd
import numpy as np

# NUMPY – PRACTICE QUESTIONS
## 1️⃣ Basics / Array Properties

In [2]:
# Create a NumPy array with values [10, 20, 30, 40].
x = np.arange(10,41,10)
x

array([10, 20, 30, 40])

In [8]:
# Find its ndim, shape, size, and dtype.
x.ndim
x.shape
x.size
x.dtype

dtype('int64')

In [13]:
# What is the difference between len(array) and array.size?
# Prove it with a 2D array.
len(x)

4

In [11]:
y = np.arange(1,10).reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
len(y)

3

In [15]:
y.size

9

In [16]:
z = np.arange(1,13).reshape(2,2,3)
z

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
len(z)

2

In [18]:
z.size

12

In [19]:
# Given a 3D array, how do you verify it is actually 3D without printing it?
z = np.arange(1,13).reshape(2,2,3)
z.ndim

3

In [20]:
z.shape

(2, 2, 3)

# 2️⃣ Reshape & Type

In [26]:
# Create a 1D array of 12 elements and reshape it into:
# (3, 4)
# (2, 2, 3)
x = np.arange(1,13)
x
x.reshape(3,4)
x.reshape(2,2,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# What error occurs if reshape dimensions don’t match size? Why?
If you attempt to reshape an array into a new shape that does not match the original number of elements,

In [27]:
# Convert a float array into an integer array. What happens to decimal values?
x.dtype

dtype('int64')

In [29]:
x = np.arange(1,10,dtype=float)
x

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
x = x.astype(int)
x
x = x.astype(float)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

# 3️⃣ Element Accessing & Slicing

In [37]:
# From a 1D array [5,10,15,20,25]:
x = np.arange(5,26,5)
x
# Access the last element
x[-1]
# Slice [10,15,20]
x[1:4]

array([10, 15, 20])

In [46]:
# From a 2D array (3×3):
x = np.arange(1,10).reshape(3,3)
x
# Extract the second row
x[1:2]
# Extract the first column
x[:,0:1]
# Extract the center element
x[1:2,1:2]

array([[5]])

In [55]:
# From a 3D array:
x = np.arange(1,13).reshape(2,2,3)
x
# Access a single element
x[1:2,0:1,1:2]
# Access an entire 2D slice
x[0,:,:]

array([[1, 2, 3],
       [4, 5, 6]])

# 4️⃣ Mathematical Operations

In [57]:
# Find max, min, argmax, and argmin of a 2D array.
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
x.max()

np.int64(9)

In [59]:
x.min()

np.int64(1)

In [60]:
x.argmax()

np.int64(8)

In [61]:
x.argmin()

np.int64(0)

In [ ]:
# What does argmax() return exactly — value or index?
# it's return  index on array

In [62]:
# Compute row-wise and column-wise maximums.
x.max(axis=0)

array([7, 8, 9])

In [63]:
x.max(axis=1)

array([3, 6, 9])

# 5️⃣ Matrix-specific

In [65]:
# Create a diagonal matrix from [1, 2, 3, 4].
x = np.diag([1,2,3,4])
x

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [66]:
# Create a 3×3 identity matrix.
x = np.eye(3,dtype=int)
x
# What is the difference between:
# diagonal matrix
# identity matrix

# Extract the diagonal elements from a square matrix.

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [67]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
z = np.diag(x,k= 2)
z

array([3])

# 🔹 PANDAS – PRACTICE QUESTIONS

# 1️⃣ Series

In [78]:
# Create a pandas Series from a list with custom index.
x = pd.Series(
    np.arange(1,10),
    index=[
        np.arange(11,100,11)
    ]
)
x
# What happens if you perform arithmetic between two Series with different indexes?


# Change the dtype of a Series.
x.astype(float)

11    1.0
22    2.0
33    3.0
44    4.0
55    5.0
66    6.0
77    7.0
88    8.0
99    9.0
dtype: float64

# 2️⃣ DataFrame Basics

In [92]:
# Create a DataFrame with columns: Name, Age, Salary.
data  = {
     'Name':['A','B','C','D'],
     'Age' : [22,23,24],
     'Salary':[1111,2222,3333]
 }
df = pd.DataFrame(data)
df
# Display:
# First 3 rows
df.head(3)
# Last 2 rows
df.tail(2)
# Rename a column without creating a new DataFrame.
df.rename(columns={'Name':'First_name'},inplace = True)
df

  First_name  Age  Salary
0          A   22    1111
1          B   23    2222
2          C   24    3333

# 3️⃣ Indexing (loc vs iloc)

In [105]:
# Select a row using loc.
# df.loc[
#     df['Age'] == 23
# ]
# Select the same row using iloc.
df.iloc[0]
# Why does loc[0] sometimes fail while iloc[0] never does?

# Select specific rows and columns together using loc.

First_name       A
Age             22
Salary        1111
Name: 0, dtype: object

# 4️⃣ Missing Values

In [117]:

# Detect missing values using:
# isnull
# df.isnull().sum()
# notna
# df.notna().sum()
# Count missing values per column.

# Replace missing values with:
# 0
# df.fillna(0)
# column mean
x = df['Age'].mean()
x
# What does fill_value do in arithmetic operations?
# incase of data is missing it will be operate what ever value is given

np.float64(23.0)

In [123]:
x = pd.Series( np.arange(5))
y = pd.Series( np.arange(11,20))
z = x.add(y)
z
df = pd.DataFrame(z)
df

      0
0  11.0
1  13.0
2  15.0
3  17.0
4  19.0
5   NaN
6   NaN
7   NaN
8   NaN

In [124]:
df.isnull()

       0
0  False
1  False
2  False
3  False
4  False
5   True
6   True
7   True
8   True

In [125]:
df.notna()

       0
0   True
1   True
2   True
3   True
4   True
5  False
6  False
7  False
8  False

In [129]:
x = df.fillna(0)
x

      0
0  11.0
1  13.0
2  15.0
3  17.0
4  19.0
5   0.0
6   0.0
7   0.0
8   0.0

# 5️⃣ Math Operations

In [147]:
# Add two DataFrames with different indexes.
d1 = pd.DataFrame(
    {
        'name':['A','B'],'roll_no':[1,2]
    }
)
d2 = pd.DataFrame(
    {
        'name':['C','D'],'roll_no':[99,98]
    }
)
df = pd.concat([d1,d2],ignore_index=True)
df

  name  roll_no
0    A        1
1    B        2
2    C       99
3    D       98

In [148]:
# Multiply a column by 10.
df.multiply(10)

         name  roll_no
0  AAAAAAAAAA       10
1  BBBBBBBBBB       20
2  CCCCCCCCCC      990
3  DDDDDDDDDD      980

In [151]:
# Perform division and floor division between two columns
df['roll_no'].div(2)

0     0.5
1     1.0
2    49.5
3    49.0
Name: roll_no, dtype: float64

In [ ]:
# What happens when indexes don’t align during operations?
# it will occure error

# 6️⃣ Merge & Concat

In [156]:
d1 = pd.DataFrame(
    {
        'name':['A','B'],'roll_no':[1,2]
    }
)
d2 = pd.DataFrame(
    {
        'name':['C','D'],'roll_no':[99,98]
    }
)
# Concatenate two DataFrames:
df = pd.concat([d1,d2])
df

  name  roll_no
0    A        1
1    B        2
0    C       99
1    D       98

In [157]:
# Row-wise
df = pd.concat([d1,d2],axis=0)
df

  name  roll_no
0    A        1
1    B        2
0    C       99
1    D       98

In [159]:
# Column-wise
df = pd.concat([d1,d2],axis=1)
df

  name  roll_no name  roll_no
0    A        1    C       99
1    B        2    D       98

In [160]:
# Reset index after concatenation.
df = pd.concat([d1,d2],ignore_index=True)
df

  name  roll_no
0    A        1
1    B        2
2    C       99
3    D       98

In [162]:
# Perform:
d1 = pd.DataFrame(
    {
        'empid':[101,102,103,104,105],
        'empname':['A','B','C','D','E'],
        'designation':['Doct','eng','adv','tea','dev']
    }
)
d2 = pd.DataFrame(
    {
        'empid':[101,102,103,106,107],
        'salary':[1000,2000,3000,4000,5000],
        'lacaton':['CL','IN','GM','UAE','UK']
    }
)
d1,d2

(   empid empname designation
 0    101       A        Doct
 1    102       B         eng
 2    103       C         adv
 3    104       D         tea
 4    105       E         dev,
    empid  salary lacaton
 0    101    1000      CL
 1    102    2000      IN
 2    103    3000      GM
 3    106    4000     UAE
 4    107    5000      UK)

In [163]:
# inner merge
inner = pd.merge(d1,d2,how='inner',on='empid')
inner

   empid empname designation  salary lacaton
0    101       A        Doct    1000      CL
1    102       B         eng    2000      IN
2    103       C         adv    3000      GM

In [164]:
# left merge
left = pd.merge(d1,d2,how='outer',on='empid')
left

   empid empname designation  salary lacaton
0    101       A        Doct  1000.0      CL
1    102       B         eng  2000.0      IN
2    103       C         adv  3000.0      GM
3    104       D         tea     NaN     NaN
4    105       E         dev     NaN     NaN
5    106     NaN         NaN  4000.0     UAE
6    107     NaN         NaN  5000.0      UK

In [165]:
# right merge
right = pd.merge(d1,d2,how='right',on='empid')
right

   empid empname designation  salary lacaton
0    101       A        Doct    1000      CL
1    102       B         eng    2000      IN
2    103       C         adv    3000      GM
3    106     NaN         NaN    4000     UAE
4    107     NaN         NaN    5000      UK

In [166]:
# outer merge
out = pd.merge(d1,d2,how='outer',on='empid')
out

   empid empname designation  salary lacaton
0    101       A        Doct  1000.0      CL
1    102       B         eng  2000.0      IN
2    103       C         adv  3000.0      GM
3    104       D         tea     NaN     NaN
4    105       E         dev     NaN     NaN
5    106     NaN         NaN  4000.0     UAE
6    107     NaN         NaN  5000.0      UK

In [ ]:
# Identify which rows appear only in an outer merge.
# all rows with nan value

# 7️⃣ Sorting & Filtering

In [ ]:
# Sort DataFrame by one column.
pd.sort_values(by='Age',ascending=False)
# Sort by multiple columns with different order.

# Filter rows where Age > 25.

# 8️⃣ Duplicates & Uniques

In [168]:
# Find unique values in a column.
out['designation'].unique()

array(['Doct', 'eng', 'adv', 'tea', 'dev', nan], dtype=object)

In [170]:
# Count frequency using value_counts
out['designation'].value_counts()

designation
Doct    1
eng     1
adv     1
tea     1
dev     1
Name: count, dtype: int64

In [171]:
# Detect duplicated rows.
out.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [174]:
# Drop duplicates based on a single column.
out.drop_duplicates(subset=['empid'])

   empid empname designation  salary lacaton
0    101       A        Doct  1000.0      CL
1    102       B         eng  2000.0      IN
2    103       C         adv  3000.0      GM
3    104       D         tea     NaN     NaN
4    105       E         dev     NaN     NaN
5    106     NaN         NaN  4000.0     UAE
6    107     NaN         NaN  5000.0      UK

In [176]:
# Drop duplicates using multiple columns (subset).
out.drop_duplicates(subset=['empid','salary'])

   empid empname designation  salary lacaton
0    101       A        Doct  1000.0      CL
1    102       B         eng  2000.0      IN
2    103       C         adv  3000.0      GM
3    104       D         tea     NaN     NaN
4    105       E         dev     NaN     NaN
5    106     NaN         NaN  4000.0     UAE
6    107     NaN         NaN  5000.0      UK