In [47]:
import pandas as pd
import numpy as np

In [48]:
d1 = pd.DataFrame(
    {
        'name':['A','B'],'roll_no':[1,2]
    }
)
d2 = pd.DataFrame(
    {
        'name':['C','D'],'roll_no':[99,98]
    }
)
d3 = pd.DataFrame(
    {
        'batch':['BCA','MCA'],'location':["blr","cochin"]
    }
)

In [49]:
d1

  name  roll_no
0    A        1
1    B        2

In [50]:
d2

  name  roll_no
0    C       99
1    D       98

In [51]:
d3

  batch location
0   BCA      blr
1   MCA   cochin

# concat

In [52]:
df = pd.concat([d1,d2])

In [53]:
df

  name  roll_no
0    A        1
1    B        2
0    C       99
1    D       98

In [54]:
df1 = pd.concat([d1,d2],ignore_index=True)
df1

  name  roll_no
0    A        1
1    B        2
2    C       99
3    D       98

In [55]:
df.reset_index()

   index name  roll_no
0      0    A        1
1      1    B        2
2      0    C       99
3      1    D       98

In [56]:
colum_base = pd.concat([d1,d3],axis=1)
colum_base

  name  roll_no batch location
0    A        1   BCA      blr
1    B        2   MCA   cochin

In [57]:
row_base = pd.concat([d1,d3])
row_base

  name  roll_no batch location
0    A      1.0   NaN      NaN
1    B      2.0   NaN      NaN
0  NaN      NaN   BCA      blr
1  NaN      NaN   MCA   cochin

In [58]:
row_base.notna()

    name  roll_no  batch  location
0   True     True  False     False
1   True     True  False     False
0  False    False   True      True
1  False    False   True      True

In [59]:
row_base.isnull()

    name  roll_no  batch  location
0  False    False   True      True
1  False    False   True      True
0   True     True  False     False
1   True     True  False     False

In [60]:
row_base.isnull().sum()

name        2
roll_no     2
batch       2
location    2
dtype: int64

In [61]:
dataframe_1 = pd.concat([d1,d2,d3],ignore_index=True)
dataframe_1

  name  roll_no batch location
0    A      1.0   NaN      NaN
1    B      2.0   NaN      NaN
2    C     99.0   NaN      NaN
3    D     98.0   NaN      NaN
4  NaN      NaN   BCA      blr
5  NaN      NaN   MCA   cochin

# Merge

In [62]:
d1 = pd.DataFrame(
    {
        'empid':[101,102,103,104,105],
        'empname':['A','B','C','D','E'],
        'designation':['Doct','eng','adv','tea','dev']
    }
)
d1

   empid empname designation
0    101       A        Doct
1    102       B         eng
2    103       C         adv
3    104       D         tea
4    105       E         dev

In [63]:
d2 = pd.DataFrame(
    {
        'empid':[101,102,103,106,107],
        'salary':[1000,2000,3000,4000,5000],
        'lacaton':['CL','IN','GM','UAE','UK']
    }
)
d2

   empid  salary lacaton
0    101    1000      CL
1    102    2000      IN
2    103    3000      GM
3    106    4000     UAE
4    107    5000      UK

## INNER JOIN

In [64]:
inner = pd.merge(d1,d2,how='inner',on='empid')
inner

   empid empname designation  salary lacaton
0    101       A        Doct    1000      CL
1    102       B         eng    2000      IN
2    103       C         adv    3000      GM

## OUTER JOIN

In [65]:
outer = pd.merge(d1,d2,how='outer',on='empid')
outer

   empid empname designation  salary lacaton
0    101       A        Doct  1000.0      CL
1    102       B         eng  2000.0      IN
2    103       C         adv  3000.0      GM
3    104       D         tea     NaN     NaN
4    105       E         dev     NaN     NaN
5    106     NaN         NaN  4000.0     UAE
6    107     NaN         NaN  5000.0      UK

## RIGHT JOIN

In [66]:
right_join = pd.merge(d1,d2,how='right',on='empid')
right_join

   empid empname designation  salary lacaton
0    101       A        Doct    1000      CL
1    102       B         eng    2000      IN
2    103       C         adv    3000      GM
3    106     NaN         NaN    4000     UAE
4    107     NaN         NaN    5000      UK

## LEFT JOIN

In [67]:
left_join = pd.merge(d1,d2,how='left',on='empid')
left_join

   empid empname designation  salary lacaton
0    101       A        Doct  1000.0      CL
1    102       B         eng  2000.0      IN
2    103       C         adv  3000.0      GM
3    104       D         tea     NaN     NaN
4    105       E         dev     NaN     NaN

In [71]:
pd.merge(d1,d2,how='right',on='empid')

   empid empname designation  salary lacaton
0    101       A        Doct    1000      CL
1    102       B         eng    2000      IN
2    103       C         adv    3000      GM
3    106     NaN         NaN    4000     UAE
4    107     NaN         NaN    5000      UK