In [38]:
import pandas as pd
import numpy as np

In [39]:
df = pd.DataFrame({
    'RollNo': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Name': ['Amit', 'Neha', 'Ravi', 'Pooja', 'Karan',
             'Sneha', 'Rahul', 'Anita', 'Vikas', 'Meena'],
    'Class': [10, 10, 9, 10, 9,
              8, 9, 8, 10, 8],
    'Marks': [78, 85, 65, 90, 72,
              88, 70, 92, 60, 75],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai',
             'Pune', 'Delhi', 'Mumbai', 'Pune', 'Delhi']
})

df

   RollNo   Name  Class  Marks    City
0       1   Amit     10     78   Delhi
1       2   Neha     10     85  Mumbai
2       3   Ravi      9     65    Pune
3       4  Pooja     10     90   Delhi
4       5  Karan      9     72  Mumbai
5       6  Sneha      8     88    Pune
6       7  Rahul      9     70   Delhi
7       8  Anita      8     92  Mumbai
8       9  Vikas     10     60    Pune
9      10  Meena      8     75   Delhi

Sort the student data by Marks (ascending order).

Sort the student data by Marks (descending order).

Sort the student data by Name (A to Z).

Sort the student data by Name (Z to A).

Sort the student data by Class.

Sort the data by City, then by Marks.

Sort the data by Class, then by Name.

Sort the students by Marks and reset the index.

Sort the data by Marks and save the changes permanently.

Sort the students by City (ascending) and Marks (descending).

Sort only students from Class 10 by Marks.

Sort students who live in Delhi by Name.

Sort the dataset using multiple columns: City → Class → Marks.

Sort the dataset and show top 3 students by Marks.

Sort the dataset and show lowest 2 students by Marks.

In [40]:
# Sort the student data by Marks (ascending order).
a_marks = df.sort_values(by='Marks')
a_marks

   RollNo   Name  Class  Marks    City
8       9  Vikas     10     60    Pune
2       3   Ravi      9     65    Pune
6       7  Rahul      9     70   Delhi
4       5  Karan      9     72  Mumbai
9      10  Meena      8     75   Delhi
0       1   Amit     10     78   Delhi
1       2   Neha     10     85  Mumbai
5       6  Sneha      8     88    Pune
3       4  Pooja     10     90   Delhi
7       8  Anita      8     92  Mumbai

In [41]:
# Sort the student data by Marks (descending order).
d_marks = df.sort_values(by='Marks',ascending=False)
d_marks

   RollNo   Name  Class  Marks    City
7       8  Anita      8     92  Mumbai
3       4  Pooja     10     90   Delhi
5       6  Sneha      8     88    Pune
1       2   Neha     10     85  Mumbai
0       1   Amit     10     78   Delhi
9      10  Meena      8     75   Delhi
4       5  Karan      9     72  Mumbai
6       7  Rahul      9     70   Delhi
2       3   Ravi      9     65    Pune
8       9  Vikas     10     60    Pune

In [42]:
# Sort the student data by Name (A to Z).
a_name = df.sort_values(by="Name")
a_name

   RollNo   Name  Class  Marks    City
0       1   Amit     10     78   Delhi
7       8  Anita      8     92  Mumbai
4       5  Karan      9     72  Mumbai
9      10  Meena      8     75   Delhi
1       2   Neha     10     85  Mumbai
3       4  Pooja     10     90   Delhi
6       7  Rahul      9     70   Delhi
2       3   Ravi      9     65    Pune
5       6  Sneha      8     88    Pune
8       9  Vikas     10     60    Pune

In [43]:
# Sort the student data by Name (Z to A).
d_name = df.sort_values(by='Name',ascending=False)
d_name

   RollNo   Name  Class  Marks    City
8       9  Vikas     10     60    Pune
5       6  Sneha      8     88    Pune
2       3   Ravi      9     65    Pune
6       7  Rahul      9     70   Delhi
3       4  Pooja     10     90   Delhi
1       2   Neha     10     85  Mumbai
9      10  Meena      8     75   Delhi
4       5  Karan      9     72  Mumbai
7       8  Anita      8     92  Mumbai
0       1   Amit     10     78   Delhi

In [44]:
# Sort the student data by Class.
by_class = df.sort_values(by="Class")
by_class

   RollNo   Name  Class  Marks    City
7       8  Anita      8     92  Mumbai
5       6  Sneha      8     88    Pune
9      10  Meena      8     75   Delhi
2       3   Ravi      9     65    Pune
6       7  Rahul      9     70   Delhi
4       5  Karan      9     72  Mumbai
0       1   Amit     10     78   Delhi
3       4  Pooja     10     90   Delhi
1       2   Neha     10     85  Mumbai
8       9  Vikas     10     60    Pune

In [45]:
# Sort the data by City, then by Marks.
c_m = df.sort_values(['City','Marks'])
c_m

   RollNo   Name  Class  Marks    City
6       7  Rahul      9     70   Delhi
9      10  Meena      8     75   Delhi
0       1   Amit     10     78   Delhi
3       4  Pooja     10     90   Delhi
4       5  Karan      9     72  Mumbai
1       2   Neha     10     85  Mumbai
7       8  Anita      8     92  Mumbai
8       9  Vikas     10     60    Pune
2       3   Ravi      9     65    Pune
5       6  Sneha      8     88    Pune

In [46]:
# Sort the data by Class, then by Name.
c_n = df.sort_values(by=['Class','Name'])
c_n

   RollNo   Name  Class  Marks    City
7       8  Anita      8     92  Mumbai
9      10  Meena      8     75   Delhi
5       6  Sneha      8     88    Pune
4       5  Karan      9     72  Mumbai
6       7  Rahul      9     70   Delhi
2       3   Ravi      9     65    Pune
0       1   Amit     10     78   Delhi
1       2   Neha     10     85  Mumbai
3       4  Pooja     10     90   Delhi
8       9  Vikas     10     60    Pune

In [47]:
# Sort the students by Marks and reset the index.
reset_index = df.sort_values(by='Marks',ignore_index=True)
reset_index

   RollNo   Name  Class  Marks    City
0       9  Vikas     10     60    Pune
1       3   Ravi      9     65    Pune
2       7  Rahul      9     70   Delhi
3       5  Karan      9     72  Mumbai
4      10  Meena      8     75   Delhi
5       1   Amit     10     78   Delhi
6       2   Neha     10     85  Mumbai
7       6  Sneha      8     88    Pune
8       4  Pooja     10     90   Delhi
9       8  Anita      8     92  Mumbai

In [48]:
# Sort the data by Marks and save the changes permanently.
change_mark = df.copy()
change_mark.sort_values(by='Marks',ignore_index=True,inplace=True)

In [49]:
change_mark

   RollNo   Name  Class  Marks    City
0       9  Vikas     10     60    Pune
1       3   Ravi      9     65    Pune
2       7  Rahul      9     70   Delhi
3       5  Karan      9     72  Mumbai
4      10  Meena      8     75   Delhi
5       1   Amit     10     78   Delhi
6       2   Neha     10     85  Mumbai
7       6  Sneha      8     88    Pune
8       4  Pooja     10     90   Delhi
9       8  Anita      8     92  Mumbai

In [50]:
# Sort the students by City (ascending) and Marks (descending).
city_mark = df.sort_values(by=['City','Marks'],ascending=[True,False])
city_mark

   RollNo   Name  Class  Marks    City
3       4  Pooja     10     90   Delhi
0       1   Amit     10     78   Delhi
9      10  Meena      8     75   Delhi
6       7  Rahul      9     70   Delhi
7       8  Anita      8     92  Mumbai
1       2   Neha     10     85  Mumbai
4       5  Karan      9     72  Mumbai
5       6  Sneha      8     88    Pune
2       3   Ravi      9     65    Pune
8       9  Vikas     10     60    Pune

In [57]:
only_10_2 = df.loc[
    df['Class'] == 10
].sort_values(by='Marks')
only_10_2

   RollNo   Name  Class  Marks    City
8       9  Vikas     10     60    Pune
0       1   Amit     10     78   Delhi
1       2   Neha     10     85  Mumbai
3       4  Pooja     10     90   Delhi

In [51]:
# Sort only students from Class 10 by Marks.
only_10 = df.loc[df['Class'] == 10].sort_values(by='Marks')
only_10

   RollNo   Name  Class  Marks    City
8       9  Vikas     10     60    Pune
0       1   Amit     10     78   Delhi
1       2   Neha     10     85  Mumbai
3       4  Pooja     10     90   Delhi

In [58]:
df.loc[
    df['City'].str.strip().str.lower() == 'delhi'
].sort_values(by='Name')

   RollNo   Name  Class  Marks   City
0       1   Amit     10     78  Delhi
9      10  Meena      8     75  Delhi
3       4  Pooja     10     90  Delhi
6       7  Rahul      9     70  Delhi

In [52]:
# Sort students who live in Delhi by Name.

live_delhi = df.loc[df['City']== 'Delhi'].sort_values(by='Name')
live_delhi

   RollNo   Name  Class  Marks   City
0       1   Amit     10     78  Delhi
9      10  Meena      8     75  Delhi
3       4  Pooja     10     90  Delhi
6       7  Rahul      9     70  Delhi

In [53]:
# Sort the dataset using multiple columns: City → Class → Marks.
multply  = df.sort_values(by=['City','Class','Marks'])
multply

   RollNo   Name  Class  Marks    City
9      10  Meena      8     75   Delhi
6       7  Rahul      9     70   Delhi
0       1   Amit     10     78   Delhi
3       4  Pooja     10     90   Delhi
7       8  Anita      8     92  Mumbai
4       5  Karan      9     72  Mumbai
1       2   Neha     10     85  Mumbai
5       6  Sneha      8     88    Pune
2       3   Ravi      9     65    Pune
8       9  Vikas     10     60    Pune

In [54]:
# Sort the dataset and show top 3 students by Marks.
top_3 = df.sort_values(by='Marks',ascending=False).iloc[:3]
top_3_2 = df.sort_values(by='Marks',ascending=False).head(3)
top_3

   RollNo   Name  Class  Marks    City
7       8  Anita      8     92  Mumbai
3       4  Pooja     10     90   Delhi
5       6  Sneha      8     88    Pune

In [55]:
top_3_2

   RollNo   Name  Class  Marks    City
7       8  Anita      8     92  Mumbai
3       4  Pooja     10     90   Delhi
5       6  Sneha      8     88    Pune

In [56]:
# Sort the dataset and show lowest 2 students by Marks.
low_2 = df.sort_values(by="Marks").head(2)
low_2

   RollNo   Name  Class  Marks  City
8       9  Vikas     10     60  Pune
2       3   Ravi      9     65  Pune