# FEATURE SCALING

In [32]:
import pandas as pd

In [33]:
data =  pd.read_csv(r"C:\Users\babus\Data_Spark\Data_analysis_practice\Data Collection\boston_data.csv")

In [34]:
data

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.15876,0.0,10.81,0.0,0.413,5.961,17.5,5.2873,4.0,305.0,19.2,376.94,9.88,21.7
1,0.10328,25.0,5.13,0.0,0.453,5.927,47.2,6.9320,8.0,284.0,19.7,396.90,9.22,19.6
2,0.34940,0.0,9.90,0.0,0.544,5.972,76.7,3.1025,4.0,304.0,18.4,396.24,9.97,20.3
3,2.73397,0.0,19.58,0.0,0.871,5.597,94.9,1.5257,5.0,403.0,14.7,351.85,21.45,15.4
4,0.04337,21.0,5.64,0.0,0.439,6.115,63.0,6.8147,4.0,243.0,16.8,393.97,9.43,20.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,9.32909,0.0,18.10,0.0,0.713,6.185,98.7,2.2616,24.0,666.0,20.2,396.90,18.13,14.1
400,51.13580,0.0,18.10,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,2.60,10.11,15.0
401,0.01501,90.0,1.21,1.0,0.401,7.923,24.8,5.8850,1.0,198.0,13.6,395.52,3.16,50.0
402,0.02055,85.0,0.74,0.0,0.410,6.383,35.7,9.1876,2.0,313.0,17.3,396.90,5.77,24.7
403,0.08244,30.0,4.93,0.0,0.428,6.481,18.5,6.1899,6.0,300.0,16.6,379.41,6.36,23.7

In [35]:
df_1 = data.copy()
df_2 = data.copy()
df_3 = data.copy()
df_4 = data.copy()

## MinMaxScaler

In [36]:
# usally around 1 to 0 default

In [37]:
df_1.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.15876,0.0,10.81,0.0,0.413,5.961,17.5,5.2873,4.0,305.0,19.2,376.94,9.88,21.7
1,0.10328,25.0,5.13,0.0,0.453,5.927,47.2,6.9320,8.0,284.0,19.7,396.90,9.22,19.6
2,0.34940,0.0,9.90,0.0,0.544,5.972,76.7,3.1025,4.0,304.0,18.4,396.24,9.97,20.3
3,2.73397,0.0,19.58,0.0,0.871,5.597,94.9,1.5257,5.0,403.0,14.7,351.85,21.45,15.4
4,0.04337,21.0,5.64,0.0,0.439,6.115,63.0,6.8147,4.0,243.0,16.8,393.97,9.43,20.5

In [38]:
def minmaxscaler(i):
    m = ( i - i.min()) / ( i.max() - i.min() )
    return m

MinAndMax =  minmaxscaler(df_1)
MinAndMax.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.001713,0.000000,0.379399,0.0,0.043841,0.459858,0.150360,0.375837,0.130435,0.225191,0.702128,0.949670,0.249694,0.371111
1,0.001090,0.263158,0.171188,0.0,0.127349,0.453344,0.456231,0.525937,0.304348,0.185115,0.755319,1.000000,0.229473,0.324444
2,0.003856,0.000000,0.346041,0.0,0.317328,0.461966,0.760041,0.176447,0.130435,0.223282,0.617021,0.998336,0.252451,0.340000
3,0.030658,0.000000,0.700880,0.0,1.000000,0.390113,0.947477,0.032544,0.173913,0.412214,0.223404,0.886404,0.604167,0.231111
4,0.000416,0.221053,0.189883,0.0,0.098121,0.489366,0.618950,0.515232,0.130435,0.106870,0.446809,0.992612,0.235907,0.344444

In [39]:
df_2.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.15876,0.0,10.81,0.0,0.413,5.961,17.5,5.2873,4.0,305.0,19.2,376.94,9.88,21.7
1,0.10328,25.0,5.13,0.0,0.453,5.927,47.2,6.9320,8.0,284.0,19.7,396.90,9.22,19.6
2,0.34940,0.0,9.90,0.0,0.544,5.972,76.7,3.1025,4.0,304.0,18.4,396.24,9.97,20.3
3,2.73397,0.0,19.58,0.0,0.871,5.597,94.9,1.5257,5.0,403.0,14.7,351.85,21.45,15.4
4,0.04337,21.0,5.64,0.0,0.439,6.115,63.0,6.8147,4.0,243.0,16.8,393.97,9.43,20.5

In [40]:
from sklearn.preprocessing import MinMaxScaler
minm = MinMaxScaler(feature_range=(-1,1))

In [41]:
mmz = minm.fit_transform(df_2)

In [42]:
mmz

array([[-0.99657322, -1.        , -0.24120235, ...,  0.89933935,
        -0.50061275, -0.25777778],
       [-0.99782039, -0.47368421, -0.65762463, ...,  1.        ,
        -0.54105392, -0.35111111],
       [-0.99228773, -1.        , -0.30791789, ...,  0.99667154,
        -0.49509804, -0.32      ],
       ...,
       [-0.99980465,  0.89473684, -0.94501466, ...,  0.9930405 ,
        -0.91237745,  1.        ],
       [-0.99968012,  0.78947368, -0.97947214, ...,  1.        ,
        -0.75245098, -0.12444444],
       [-0.99828886, -0.36842105, -0.67228739, ...,  0.91179585,
        -0.71629902, -0.16888889]], shape=(404, 14))

In [43]:
df_2 = pd.DataFrame(mmz,columns=df_1.columns)
df_2.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,-0.996573,-1.000000,-0.241202,-1.0,-0.912317,-0.080284,-0.699279,-0.248325,-0.739130,-0.549618,0.404255,0.899339,-0.500613,-0.257778
1,-0.997820,-0.473684,-0.657625,-1.0,-0.745303,-0.093313,-0.087539,0.051874,-0.391304,-0.629771,0.510638,1.000000,-0.541054,-0.351111
2,-0.992288,-1.000000,-0.307918,-1.0,-0.365344,-0.076068,0.520082,-0.647106,-0.739130,-0.553435,0.234043,0.996672,-0.495098,-0.320000
3,-0.938684,-1.000000,0.401760,-1.0,1.000000,-0.219774,0.894954,-0.934912,-0.652174,-0.175573,-0.553191,0.772808,0.208333,-0.537778
4,-0.999167,-0.557895,-0.620235,-1.0,-0.803758,-0.021268,0.237899,0.030463,-0.739130,-0.786260,-0.106383,0.985224,-0.528186,-0.311111

In [44]:
minmm = MinMaxScaler(feature_range=(-1,1))

In [45]:
mmz = minmm.fit_transform(df_2)

In [46]:
mmz

array([[-0.99657322, -1.        , -0.24120235, ...,  0.89933935,
        -0.50061275, -0.25777778],
       [-0.99782039, -0.47368421, -0.65762463, ...,  1.        ,
        -0.54105392, -0.35111111],
       [-0.99228773, -1.        , -0.30791789, ...,  0.99667154,
        -0.49509804, -0.32      ],
       ...,
       [-0.99980465,  0.89473684, -0.94501466, ...,  0.9930405 ,
        -0.91237745,  1.        ],
       [-0.99968012,  0.78947368, -0.97947214, ...,  1.        ,
        -0.75245098, -0.12444444],
       [-0.99828886, -0.36842105, -0.67228739, ...,  0.91179585,
        -0.71629902, -0.16888889]], shape=(404, 14))

## StandardScaler

In [47]:
# usally around -3 to 3 range

In [48]:
df_3.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.15876,0.0,10.81,0.0,0.413,5.961,17.5,5.2873,4.0,305.0,19.2,376.94,9.88,21.7
1,0.10328,25.0,5.13,0.0,0.453,5.927,47.2,6.9320,8.0,284.0,19.7,396.90,9.22,19.6
2,0.34940,0.0,9.90,0.0,0.544,5.972,76.7,3.1025,4.0,304.0,18.4,396.24,9.97,20.3
3,2.73397,0.0,19.58,0.0,0.871,5.597,94.9,1.5257,5.0,403.0,14.7,351.85,21.45,15.4
4,0.04337,21.0,5.64,0.0,0.439,6.115,63.0,6.8147,4.0,243.0,16.8,393.97,9.43,20.5

In [49]:
def standardscal(i):
    x = ( i - i.mean()) / i.std()
    return x

standardscal(df_3).head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,-0.399394,-0.476559,-0.055746,-0.27255,-1.224937,-0.503751,-1.820761,0.705068,-0.660646,-0.623639,0.351322,0.231473,-0.392616,-0.069297
1,-0.405597,0.657036,-0.889212,-0.27255,-0.883991,-0.554060,-0.762546,1.484577,-0.207888,-0.746393,0.583848,0.442713,-0.487921,-0.306933
2,-0.378079,-0.476559,-0.189276,-0.27255,-0.108339,-0.487475,0.288542,-0.330424,-0.660646,-0.629484,-0.020720,0.435728,-0.379620,-0.227721
3,-0.111466,-0.476559,1.231139,-0.27255,2.678894,-1.042348,0.937010,-1.077752,-0.547456,-0.050786,-1.741415,-0.034059,1.278100,-0.782207
4,-0.412296,0.475661,-0.814376,-0.27255,-1.003322,-0.275884,-0.199590,1.428983,-0.660646,-0.986056,-0.764804,0.411704,-0.457597,-0.205089

In [50]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x = ss.fit_transform(df_3)
df_3 = pd.DataFrame(x,columns=data.columns)
df_3.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,-0.399890,-0.477150,-0.055815,-0.272888,-1.226456,-0.504376,-1.823018,0.705942,-0.661465,-0.624412,0.351757,0.231760,-0.393103,-0.069383
1,-0.406100,0.657851,-0.890315,-0.272888,-0.885087,-0.554747,-0.763492,1.486418,-0.208145,-0.747319,0.584572,0.443262,-0.488526,-0.307314
2,-0.378548,-0.477150,-0.189511,-0.272888,-0.108473,-0.488080,0.288900,-0.330833,-0.661465,-0.630265,-0.020746,0.436268,-0.380091,-0.228004
3,-0.111604,-0.477150,1.232665,-0.272888,2.682216,-1.043641,0.938172,-1.079088,-0.548135,-0.050849,-1.743574,-0.034101,1.279685,-0.783177
4,-0.412807,0.476251,-0.815386,-0.272888,-1.004566,-0.276226,-0.199838,1.430755,-0.661465,-0.987279,-0.765753,0.412215,-0.458164,-0.205343

# Robust_Scaler

In [51]:
df_4.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.15876,0.0,10.81,0.0,0.413,5.961,17.5,5.2873,4.0,305.0,19.2,376.94,9.88,21.7
1,0.10328,25.0,5.13,0.0,0.453,5.927,47.2,6.9320,8.0,284.0,19.7,396.90,9.22,19.6
2,0.34940,0.0,9.90,0.0,0.544,5.972,76.7,3.1025,4.0,304.0,18.4,396.24,9.97,20.3
3,2.73397,0.0,19.58,0.0,0.871,5.597,94.9,1.5257,5.0,403.0,14.7,351.85,21.45,15.4
4,0.04337,21.0,5.64,0.0,0.439,6.115,63.0,6.8147,4.0,243.0,16.8,393.97,9.43,20.5

In [52]:
def robust_scaler(x):
    q1 = x.quantile(0.25)
    q3 = x.quantile(0.75)
    iqr = q3 - q1
    new_rs = (x - x.median())  / iqr
    return new_rs

robust_scaler(df_4).head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,-0.023913,0.00,0.078621,NaN,-0.702247,-0.370957,-1.222337,0.663588,-0.05,-0.064935,0.070796,-0.663223,-0.141688,0.037975
1,-0.037886,2.00,-0.361348,NaN,-0.477528,-0.417756,-0.608066,1.188339,0.15,-0.119481,0.247788,0.273976,-0.209207,-0.227848
2,0.024097,0.00,0.008133,NaN,0.033708,-0.355816,0.002068,-0.033485,-0.05,-0.067532,-0.212389,0.242986,-0.132481,-0.139241
3,0.624627,0.00,0.757940,NaN,1.870787,-0.871989,0.378490,-0.536572,0.00,0.189610,-1.522124,-1.841296,1.041944,-0.759494
4,-0.052973,1.68,-0.321844,NaN,-0.556180,-0.158981,-0.281282,1.150913,-0.05,-0.225974,-0.778761,0.136401,-0.187724,-0.113924

In [53]:
from sklearn.preprocessing import RobustScaler

In [54]:
scaler = RobustScaler()
df_4 = scaler.fit_transform(df_4)
df_4 = pd.DataFrame(df_4,columns=data.columns)
df_4.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,-0.023913,0.00,0.078621,0.0,-0.702247,-0.370957,-1.222337,0.663588,-0.05,-0.064935,0.070796,-0.663223,-0.141688,0.037975
1,-0.037886,2.00,-0.361348,0.0,-0.477528,-0.417756,-0.608066,1.188339,0.15,-0.119481,0.247788,0.273976,-0.209207,-0.227848
2,0.024097,0.00,0.008133,0.0,0.033708,-0.355816,0.002068,-0.033485,-0.05,-0.067532,-0.212389,0.242986,-0.132481,-0.139241
3,0.624627,0.00,0.757940,0.0,1.870787,-0.871989,0.378490,-0.536572,0.00,0.189610,-1.522124,-1.841296,1.041944,-0.759494
4,-0.052973,1.68,-0.321844,0.0,-0.556180,-0.158981,-0.281282,1.150913,-0.05,-0.225974,-0.778761,0.136401,-0.187724,-0.113924