In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

In [4]:
data

{'Name': ['Alice', 'Bob', 'Charlie'],
 'Age': [25, 30, 35],
 'City': ['New York', 'Los Angeles', 'Chicago']}

In [5]:
df = pd.DataFrame(data,index=['a','b','c'])

In [6]:
df

      Name  Age         City
a    Alice   25     New York
b      Bob   30  Los Angeles
c  Charlie   35      Chicago

In [7]:
il = df.iloc[1]
il

Name            Bob
Age              30
City    Los Angeles
Name: b, dtype: object

In [8]:
lo = df.loc[df['Age'] > 30]
lo

      Name  Age     City
c  Charlie   35  Chicago

In [9]:
lo = df.loc[
    (df['Age'] >= 30) &
    (df['City'].str.strip().str.lower() == 'los angeles')
]
lo

  Name  Age         City
b  Bob   30  Los Angeles